export const otherItems = [
    {
        id: 'farm_expansion',
        name: 'Розширення',
        type: 'OTHER',
        mechanic: 'expand_farm',
        price: 25,
        priceCurrency: 'rubies',
        plantingXp: 0,
        requiredLevel: 1,
        sortOrder: 1,
        shopImage: '/assets/ui/add_pole.png',
        shopIcon: '🗺️',
        growthImages: ['/assets/ui/add_pole.png'],
        footprint: { width: 1, height: 1 },
        placementSurface: 'grass',
        access: 'all',
    },
    {
        id: 'fertilizer_30m',
        name: 'Добриво · 30 хв',
        type: 'OTHER',
        mechanic: 'accelerate_growth',
        accelerationMs: 30 * 60 * 1000,
        price: 1,
        priceCurrency: 'rubies',
        plantingXp: 0,
        requiredLevel: 1,
        sortOrder: 2,
        shopImage: '/assets/fertilizers/fertilizer_30m.png',
        shopIcon: '🧪',
        access: 'all',
    },
    {
        id: 'fertilizer_4h',
        name: 'Добриво · 4 год',
        type: 'OTHER',
        mechanic: 'accelerate_growth',
        accelerationMs: 4 * 60 * 60 * 1000,
        price: 5,
        priceCurrency: 'rubies',
        plantingXp: 0,
        requiredLevel: 1,
        sortOrder: 3,
        shopImage: '/assets/fertilizers/fertilizer_4h.png',
        shopIcon: '🧪',
        access: 'all',
    },
    {
        id: 'fertilizer_16h',
        name: 'Добриво · 16 год',
        type: 'OTHER',
        mechanic: 'accelerate_growth',
        accelerationMs: 16 * 60 * 60 * 1000,
        price: 15,
        priceCurrency: 'rubies',
        plantingXp: 0,
        requiredLevel: 1,
        sortOrder: 4,
        shopImage: '/assets/fertilizers/fertilizer_16h.png',
        shopIcon: '🧪',
        access: 'all',
    },
];